/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStocksDotxmlRouteImport } from './routes/sitemap-stocks[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapCalculatorsDotxmlRouteImport } from './routes/sitemap-calculators[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketDataRouteImport } from './routes/market-data'
import { Route as InvestingCalculatorsRouteImport } from './routes/investing-calculators'
import { Route as HowToCalculateSipReturnsRouteImport } from './routes/how-to-calculate-sip-returns'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiUsageRouteImport } from './routes/ai-usage'
import { Route as AiDisclaimerRouteImport } from './routes/ai-disclaimer'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksIndexRouteImport } from './routes/stocks.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as StocksSymbolRouteImport } from './routes/stocks.$symbol'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as CalcTypeRouteImport } from './routes/calc.$type'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStocksDotxmlRoute = SitemapStocksDotxmlRouteImport.update({
  id: '/sitemap-stocks.xml',
  path: '/sitemap-stocks.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCalculatorsDotxmlRoute =
  SitemapCalculatorsDotxmlRouteImport.update({
    id: '/sitemap-calculators.xml',
    path: '/sitemap-calculators.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketDataRoute = MarketDataRouteImport.update({
  id: '/market-data',
  path: '/market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingCalculatorsRoute = InvestingCalculatorsRouteImport.update({
  id: '/investing-calculators',
  path: '/investing-calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToCalculateSipReturnsRoute =
  HowToCalculateSipReturnsRouteImport.update({
    id: '/how-to-calculate-sip-returns',
    path: '/how-to-calculate-sip-returns',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiUsageRoute = AiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDisclaimerRoute = AiDisclaimerRouteImport.update({
  id: '/ai-disclaimer',
  path: '/ai-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksIndexRoute = StocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StocksRoute,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => StocksRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CalcTypeRoute = CalcTypeRouteImport.update({
  id: '/calc/$type',
  path: '/calc/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai': typeof AiRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/ai-usage': typeof AiUsageRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/how-to-calculate-sip-returns': typeof HowToCalculateSipReturnsRoute
  '/investing-calculators': typeof InvestingCalculatorsRoute
  '/market-data': typeof MarketDataRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap-calculators.xml': typeof SitemapCalculatorsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-stocks.xml': typeof SitemapStocksDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRouteWithChildren
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/stt': typeof ApiSttRoute
  '/calc/$type': typeof CalcTypeRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/stocks/': typeof StocksIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai': typeof AiRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/ai-usage': typeof AiUsageRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/how-to-calculate-sip-returns': typeof HowToCalculateSipReturnsRoute
  '/investing-calculators': typeof InvestingCalculatorsRoute
  '/market-data': typeof MarketDataRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap-calculators.xml': typeof SitemapCalculatorsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-stocks.xml': typeof SitemapStocksDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/stt': typeof ApiSttRoute
  '/calc/$type': typeof CalcTypeRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/stocks': typeof StocksIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai': typeof AiRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/ai-usage': typeof AiUsageRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/how-to-calculate-sip-returns': typeof HowToCalculateSipReturnsRoute
  '/investing-calculators': typeof InvestingCalculatorsRoute
  '/market-data': typeof MarketDataRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap-calculators.xml': typeof SitemapCalculatorsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-stocks.xml': typeof SitemapStocksDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRouteWithChildren
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/stt': typeof ApiSttRoute
  '/calc/$type': typeof CalcTypeRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/stocks/': typeof StocksIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/acceptable-use'
    | '/ai'
    | '/ai-disclaimer'
    | '/ai-usage'
    | '/auth'
    | '/calculators'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/disclaimer'
    | '/faq'
    | '/how-to-calculate-sip-returns'
    | '/investing-calculators'
    | '/market-data'
    | '/mcp'
    | '/news'
    | '/offline'
    | '/privacy'
    | '/security'
    | '/sitemap-calculators.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-stocks.xml'
    | '/sitemap.xml'
    | '/stocks'
    | '/terms'
    | '/thank-you'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/api/stt'
    | '/calc/$type'
    | '/case-studies/$slug'
    | '/r/$slug'
    | '/stocks/$symbol'
    | '/case-studies/'
    | '/stocks/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/acceptable-use'
    | '/ai'
    | '/ai-disclaimer'
    | '/ai-usage'
    | '/auth'
    | '/calculators'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/disclaimer'
    | '/faq'
    | '/how-to-calculate-sip-returns'
    | '/investing-calculators'
    | '/market-data'
    | '/mcp'
    | '/news'
    | '/offline'
    | '/privacy'
    | '/security'
    | '/sitemap-calculators.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-stocks.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/api/stt'
    | '/calc/$type'
    | '/case-studies/$slug'
    | '/r/$slug'
    | '/stocks/$symbol'
    | '/case-studies'
    | '/stocks'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/404'
    | '/about'
    | '/acceptable-use'
    | '/ai'
    | '/ai-disclaimer'
    | '/ai-usage'
    | '/auth'
    | '/calculators'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/disclaimer'
    | '/faq'
    | '/how-to-calculate-sip-returns'
    | '/investing-calculators'
    | '/market-data'
    | '/mcp'
    | '/news'
    | '/offline'
    | '/privacy'
    | '/security'
    | '/sitemap-calculators.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-stocks.xml'
    | '/sitemap.xml'
    | '/stocks'
    | '/terms'
    | '/thank-you'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/api/stt'
    | '/calc/$type'
    | '/case-studies/$slug'
    | '/r/$slug'
    | '/stocks/$symbol'
    | '/case-studies/'
    | '/stocks/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  AiRoute: typeof AiRoute
  AiDisclaimerRoute: typeof AiDisclaimerRoute
  AiUsageRoute: typeof AiUsageRoute
  AuthRoute: typeof AuthRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CopyrightRoute: typeof CopyrightRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  HowToCalculateSipReturnsRoute: typeof HowToCalculateSipReturnsRoute
  InvestingCalculatorsRoute: typeof InvestingCalculatorsRoute
  MarketDataRoute: typeof MarketDataRoute
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapCalculatorsDotxmlRoute: typeof SitemapCalculatorsDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapStocksDotxmlRoute: typeof SitemapStocksDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StocksRoute: typeof StocksRouteWithChildren
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiSttRoute: typeof ApiSttRoute
  CalcTypeRoute: typeof CalcTypeRoute
  RSlugRoute: typeof RSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-stocks.xml': {
      id: '/sitemap-stocks.xml'
      path: '/sitemap-stocks.xml'
      fullPath: '/sitemap-stocks.xml'
      preLoaderRoute: typeof SitemapStocksDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-calculators.xml': {
      id: '/sitemap-calculators.xml'
      path: '/sitemap-calculators.xml'
      fullPath: '/sitemap-calculators.xml'
      preLoaderRoute: typeof SitemapCalculatorsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-data': {
      id: '/market-data'
      path: '/market-data'
      fullPath: '/market-data'
      preLoaderRoute: typeof MarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing-calculators': {
      id: '/investing-calculators'
      path: '/investing-calculators'
      fullPath: '/investing-calculators'
      preLoaderRoute: typeof InvestingCalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-calculate-sip-returns': {
      id: '/how-to-calculate-sip-returns'
      path: '/how-to-calculate-sip-returns'
      fullPath: '/how-to-calculate-sip-returns'
      preLoaderRoute: typeof HowToCalculateSipReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-usage': {
      id: '/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-disclaimer': {
      id: '/ai-disclaimer'
      path: '/ai-disclaimer'
      fullPath: '/ai-disclaimer'
      preLoaderRoute: typeof AiDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/': {
      id: '/stocks/'
      path: '/'
      fullPath: '/stocks/'
      preLoaderRoute: typeof StocksIndexRouteImport
      parentRoute: typeof StocksRoute
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof StocksRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/calc/$type': {
      id: '/calc/$type'
      path: '/calc/$type'
      fullPath: '/calc/$type'
      preLoaderRoute: typeof CalcTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface StocksRouteChildren {
  StocksSymbolRoute: typeof StocksSymbolRoute
  StocksIndexRoute: typeof StocksIndexRoute
}

const StocksRouteChildren: StocksRouteChildren = {
  StocksSymbolRoute: StocksSymbolRoute,
  StocksIndexRoute: StocksIndexRoute,
}

const StocksRouteWithChildren =
  StocksRoute._addFileChildren(StocksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  AiRoute: AiRoute,
  AiDisclaimerRoute: AiDisclaimerRoute,
  AiUsageRoute: AiUsageRoute,
  AuthRoute: AuthRoute,
  CalculatorsRoute: CalculatorsRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CopyrightRoute: CopyrightRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  HowToCalculateSipReturnsRoute: HowToCalculateSipReturnsRoute,
  InvestingCalculatorsRoute: InvestingCalculatorsRoute,
  MarketDataRoute: MarketDataRoute,
  McpRoute: McpRoute,
  NewsRoute: NewsRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SitemapCalculatorsDotxmlRoute: SitemapCalculatorsDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapStocksDotxmlRoute: SitemapStocksDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StocksRoute: StocksRouteWithChildren,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiSttRoute: ApiSttRoute,
  CalcTypeRoute: CalcTypeRoute,
  RSlugRoute: RSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
